server:
  port: 7070
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis:
  #mapper配置文件
  #扫描XML文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #开启Mybatis日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: itheima
    user-ttl: 7200000000000
    user-token-name: authentication
  aliyunoss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  redisconf:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
  wechat:
    appid: ${sky.wechat1.appid}
    secret: ${sky.wechat1.secret}

  shop:
      address: 北京市海淀区上地十街10号
    #设置商户号等等
#    mchid: ${sky.wechat.mchid}
#    mchSerialNo: ${sky.wechat.mchSerialNo}
#    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
#    apiV3Key: ${sky.wechat.apiV3Key}
#    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
#    notifyUrl: ${sky.wechat.notifyUrl}
#    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}


#  servlet:
#    multipart:
#      max-file-size: 10MB      # 设置单个文件的最大上传大小
#      max-request-size: 10MB   # 设置一次请求的最大上传大小（包括所有文件）
#
#  tomcat:
#    max-swallow-size: 50MB  # 设置最大吞吐量
#    max-http-post-size: 50MB  # 设置最大POST请求体大小
